const keyMirror = require('key-mirror');

export default keyMirror({
  // User connection type
  USER_CONNECT_VIA_FACEBOOK: null,
  USER_CONNECT_VIA_TWITTER: null,

  // Parse empty model type
  PARSE_EMPTY_MODEL_ID: null,

  // Email template type
  EMAILS_TEMPLATE_VERIFY_REMOVE_USER: null,

  // Confirm Delete user form type
  CONFIRM_DELETE_USER_MAIN: null,
  CONFIRM_DELETE_USER_RESULT: null,


  MENU_ITEM_ADD_OR_EDIT_POST: null,

  // User single page type
  PAGE_USER_PROFILE_FOR_INFORMATION: null,
  PAGE_USER_PROFILE_FOR_EDIT: null,

  // User Profile left menus type
  USER_PROFILE_LEFT_SIDE_UPVOTE: null,
  USER_PROFILE_LEFT_SIDE_DOWNVOTE: null,
  USER_PROFILE_LEFT_SIDE_SUBMITTED_ARTICLES: null,

  // Voting action type
  VOTING_FOR_UPVOTE: null,
  VOTING_FOR_DOWNVOTE: null,

  // Voting views type
  VOTING_POSTS_LIST_ITEM: null,
  VOTING_ARTICLE_HEADER_ITEM: null,
  VOTING_RELATED_POSTS_LIST_ITEM: null,

  // App Overlay type
  APP_OVERLAY_SHOW_MODEL: null,
  APP_OVERLAY_DISMISS_MODEL: null,

  OVERLAY_TYPE_MORE_TOPICS: null,
  OVERLAY_TYPE_LOGIN_UI: null,
  OVERLAY_TYPE_LOGGED_USER_MENU: null,
  OVERLAY_TYPE_ARTICLE_SAVE_BUTTON: null,
  OVERLAY_TYPE_SUBMIT_FLAG: null,
  OVERLAY_TYPE_MESSAGES_LIST: null,
  OVERLAY_TYPE_USER_DELETE_CONFIRM: null,


  // Posts Voting type
  POSTS_VOTING_LIST_UPVOTE: null,
  POSTS_VOTING_LIST_DOWNVOTE: null,
  POSTS_VOTING_ARTICLE_UPVOTE: null,
  POSTS_VOTING_ARTICLE_DOWNVOTE: null,

  // Banner top type
  BANNER_HIDEN_TOP_HERO_PANEL: null,
  BANNER_HIDDEN_TOP_NEWSLETTER_PANEL: null,

  // Comment table type
  COMMENTS_TABLE_NORMAL: null,
  COMMENTS_TABLE_FOR_POST: null,

  // Table Options
  APP_TABLE_OPTIONS_CLOSE: null,
  APP_TABLE_OPTIONS_OPEN_OPTIONS: null,
  APP_TABLE_OPTIONS_OPEN_HELP: null,

  // Post Status
  POST_MODEL_STATUS_UNKNOW: null,
  POST_MODEL_STATUS_APPROVED: null,
  POST_MODEL_STATUS_PENDING: null,
  POST_MODEL_STATUS_SPAM_DRAFT: null,


  // Table edit type
  EDIT_TABLE_SINGLE_MODEL: null,
  EDIT_TABLE_MULTIPLE_MODEL: null,
  EDIT_TABLE_RESET: null,

  // Table actions type
  TABLE_ACTIONS_TYPE_NONE: null,
  TABLE_ACTIONS_TYPE_EDIT: null,
  TABLE_ACTIONS_TYPE_MOVE_TRASH: null,
  TABLE_ACTIONS_TYPE_AS_PUBLISHED: null,
  TABLE_ACTIONS_TYPE_RESTORE: null,
  TABLE_ACTIONS_TYPE_DELETE: null,
  TABLE_ACTIONS_TYPE_APPROVE: null,
  TABLE_ACTIONS_TYPE_UNAPPROVE: null,
  TABLE_ACTIONS_TYPE_MAKE_AS_SPAM: null,
  TABLE_ACTIONS_TYPE_NOT_SPAM: null,

  // For topics
  TABLE_ACTIONS_TYPE_TOPIC_MAKE_AS_ACTIVE: null,
  TABLE_ACTIONS_TYPE_TOPIC_NOT_ACTIVE: null,
  TABLE_ACTIONS_TYPE_MAKE_AS_FILTER: null,
  TABLE_ACTIONS_TYPE_NOT_FILTER: null,
  // Users
  TABLE_ACTIONS_TYPE_USER_ROLE_NONE: null,
  TABLE_ACTIONS_TYPE_USER_ROLE_NORMAL: null,
  TABLE_ACTIONS_TYPE_USER_ROLE_ADMINISTRATOR: null,


  // Table Column Type
  TABLE_LIST_COLUMN_POST_SOURCE_FROM: null,
  TABLE_LIST_COLUMN_POST_AUTHOR: null,
  TABLE_LIST_COLUMN_POST_TOPIC: null,

  // Photos Browser Type
  PHOTOS_BROWSER_PAGE_NORMAL: null,
  PHOTOS_BROWSER_PAGE_FOR_USER_PROFILE: null,

  //Alert Type
  ALERT_TYPE_SUCCESS: null,
  ALERT_TYPE_ERROR: null,
  ALERT_TYPE_INFO: null,

  // Events List type
  EVENTS_LIST_FOR_RESTAURANT: null,
  EVENTS_LIST_FOR_USER: null,

  // Photo browser title
  PHOTO_BROWSER_NORMAL_TITLE: null,
  PHOTO_BROWSER_LOGGED_USER_TITLE: null,

  // Upload Image
  UPLOAD_IMAGE_FILE_DROP: null,
  UPLOAD_IMAGE_FILE_PREVIEW: null,

  // invoke parse cloud.
  CLOUD_STATISTIC_FOR_POSTS: null,
  CLOUD_STATISTIC_FOR_TOPICS: null,
  CLOUD_STATISTIC_FOR_COMMENTS: null,
  CLOUD_STATISTIC_FOR_FLAGS: null,
  CLOUD_STATISTIC_FOR_USERS: null,
  CLOUD_RESTAURANT_ADDRESS: null,
  CLOUD_EMPTY_TRASH_FOR_POSTS: null,
  CLOUD_EMPTY_TRASH_FOR_TOPICS: null,
  CLOUD_EMPTY_TRASH_FOR_COMMENTS: null,
  CLOUD_EMPTY_TRASH_FOR_FLAGS: null,
  CLOUD_POSTS_COUNTS_FOR_TOPICS: null,
  CLOUD_POSTS_COUNTS_FOR_USERS: null,
  CLOUD_STATISTIC_FOR_LOGGED_USERS: null,

  EMAIL_SEND_CLOUD_MODEL: null,


  // Google Address
  RESTAURANT_CLOUD_ADDRESS_MODEL: null,

  // Review sort tags
  REVIEW_SORT_NORMAL: null,
  REVIEW_SORT_NEWEST: null,
  REVIEW_SORT_OLDEST: null,
  REVIEW_SORT_HIGHEST: null,
  REVIEW_SORT_LOWEST: null,

  // Review List Type
  REVIEW_LIST_TYPE_NORMAL: null,
  REVIEW_LIST_TYPE_USER_PROFILE_ABOUT: null,
  REVIEW_LIST_TYPE_USER_PROFILE_REVIEWS: null,

  // UserSingle Form Type
  // 1.1 LOGGED user left menus.
  LOGGED_USER_MENU_ABOUT: null,
  LOGGED_USER_MENU_REVIEWS: null,
  LOGGED_USER_MENU_BROWSER_PHOTOS: null,
  LOGGED_USER_MENU_EVENTS: null,

  // 1.2 Edit User.
  LOGGED_USER_EDIT_FORM: null,

  // App alert
  SHOW_ALERT_MESSAGE: null,
  DISMISS_ALERT_MESSAGE: null,

  // Page form types
  PAGE_MAIN_FORM: null,
  PAGE_MAIN_FORM_WITH_PHOTO_OVERLAY: null,
  PAGE_PHOTOS_BROWSER_FORM: null,
  PAGE_PHOTOS_BROWSER_FORM_WITH_PHOTO_OVERLAY: null,
  PAGE_OVERLAY_SELECTED_PHOTO_FORM: null,
  PAGE_SINGLE_SELECTED_PHOTO_FORM: null,

  // Home More Menus
  MENU_TABLE_TYPE_POSTS: null,
  MENU_ITEM_ADD_OR_EDIT_EVENT: null,
  MENU_ITEM_ADD_OR_EDIT_RECIPE: null,
  MENU_ITEM_ADD_OR_EDIT_USER: null,
  MENU_ITEM_ADD_OR_EDIT_REVIEW: null,
  MENU_ITEM_SEARCH_RESTAURANTS: null,
  MENU_ITEM_MANAGE_FRIENDS: null,
  MENU_ITEM_READ_REVIEWS: null,

  // Model Form Mode
  MODEL_FORM_TYPE_NEW: null,
  MODEL_FORM_TYPE_EDIT: null,

  // Edit Model
  EDIT_MODEL_TOGGLE_TYPE: null,
  TABLE_SELECT_ALL_ROWS_TOGGLE_TYPE: null,
  TABLE_SELECTED_ROWS_TOGGLE_TYPE: null,
  TABLE_SINGLE_ROWS_EDIT_TYPE: null,
  TABLE_SINGLE_ROWS_CANCEL_EDIT_TYPE: null,
  TABLE_SELECTED_ROWS_EDIT_TYPE: null,
  TABLE_SELECTED_ROWS_CANCEL_EDIT_TYPE: null,

  TABLE_CHANGE_ACTION_TYPE: null,
  TABLE_CHANGE_ACTION_TYPE_USER_ROLE: null,

  ON_EDIT_MODEL_FORM_FIELD_CHANGE: null,
  ON_RESTAURANT_MODEL_FORM_ADDRESS_FIELD_CHANGE: null,
  SAVE_MODEL_REQUEST: null,
  UPDATE_MODEL_REQUEST: null,
  UPDATE_MODEL_SUCCESS: null,
  UPDATE_MODEL_FAILURE: null,

  REMOVE_MODEL_DONE: null,
  WRITE_MODEL_DONE: null,
  WRITE_VOTING_USERS_DONE: null,

  // Parse Object
  PARSE_CONFIGURE: null,
  PARSE_SETTINGS: null,
  PARSE_POSTS: null,
  PARSE_TOPICS: null,
  PARSE_FLAGS: null,
  PARSE_USERS: null,
  PARSE_COMMENTS: null,
  PARSE_SITES: null,
  PARSE_HISTORY: null,

  // Login UI
  LOGIN_FORM_TYPE_MAIN: null,
  LOGIN_FORM_TYPE_LOGIN: null,
  LOGIN_FORM_TYPE_REGISTER: null,
  LOGIN_FORM_TYPE_LOG_OUT: null,
  LOGIN_FORM_TYPE_FORGOTPASSWORD: null,
  LOGIN_FORM_TYPE_RESET_PASSWD: null,


  // User Profile Type
  USERPROFILE_TYPE_UPVOTE: null,
  USERPROFILE_TYPE_DOWNVOTE: null,
  USERPROFILE_TYPE_SUBMITTED_POSTS: null,
  USERPROFILE_TYPE_FOLDER_LIST: null,

  // IEAUserProfileAboutLayout Event Type
  USERPROFILE_RESET: null,
  USERPROFILE_LOADED: null,

  // Voting button types
  VOTE_BUTTON_LIST_UPVOTE: null,
  VOTE_BUTTON_LIST_DOWNVOTE: null,
  VOTE_BUTTON_ARTICLE_UPVOTE: null,
  VOTE_BUTTON_ARTICLE_DOWNVOTE: null,
  VOTE_BUTTON_RELATED_UPVOTE: null,
  VOTE_BUTTON_RELATED_DOWNVOTE: null,


  // Voting
  POSTS_UPVOTE: null,
  POSTS_DOWNVOTE: null,
  POSTS_UPVOTE_CACEL: null,
  POSTS_DOWNVOTE_CACEL: null,

  POSTS_VOTING_DONE: null,

  // Users
  LOGGED_IN: null,
  LOGGED_OUT: null,
  SET_SHARING: null,
  RESET_NUXES: null,


  // For dashboard
  DASHBOARD_EDIT_ALL_ROWS: null,
  DASHBOARD_EDIT_SINGLE_ROW: null,
  DASHBOARD_EDIT_SINGLE_ROW_CANCEL: null,

  TOGGLE_TABLE_ROW_CHECKBOX: null,
  TOGGLE_TABLE_ROW_ALL_CHECKBOXS: null,

  DASHBOARD_LOADED_PAGINATION: null,
  DASHBOARD_LOADED_TOPICS: null,
  DASHBOARD_RESET: null,

  // PostHome, PostDaily
  LIST_VIEW_LOADED_BY_TYPE: null,
  LIST_VIEW_LOADED_RESTAURANTS: null,
  LIST_VIEW_LOADED_EVENTS: null,
  LIST_VIEW_LOADED_ORDERED_USERS: null,
  LIST_VIEW_LOADED_RECIPES: null,
  LIST_VIEW_LOADED_USERS: null,
  LOADED_PHOTOS_BROWSER: null,

  // Detailed Page(Restaurants,Events)
  OVERLAY_LOADED_MODEL_PAGE: null,
  OVERLAY_LOADED_MODEL_RESET: null,
  STATISTIC_CLOUD_MODEL: null,

  SET_PLATFORM: null,
  SET_VERSION: null,

  LOGIN_VIA_SOCIAL: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  REQUEST_API: null,
  RESET_ERROR: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  ON_SHIPMENT_FORM_FIELD_CHANGE: null,
  NEW_SHIPMENT: null,
  NEW_SHIPMENT_REQUEST: null,
  NEW_SHIPMENT_SUCCESS: null,
  NEW_SHIPMENT_FAILURE: null,

  GET_SHIPMENTS_REQUEST: null,
  GET_SHIPMENTS_SUCCESS: null,
  GET_SHIPMENTS_FAILURE: null,

  ON_SHIPMENT_SAVED: null

});
